<?php

namespace TenisClubBundle\Repository;

/**
 * EntidadGFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadGFRepository extends \Doctrine\ORM\EntityRepository
{
}
