<?php

namespace TenisClubBundle\Repository;

/**
 * LugarPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LugarPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
